---
# file defaults/{{ project }}
# Project for sig-paas: origin or openshift-ansible
project: origin

# Path to repo for {{ project }}
openshift_repo_path: /root/{{ project }}

# Architecture
arch: x86_64

# Cleanup before building {{ project }} from source
cleanup: false
