---

# Add in here direct RPM links, for things that are still pending repodata
- name: Direct RPM links, for things that are still pending repodata
  command: yum -y localinstall {{ item }}
  with_items:
    - https://kojipkgs.fedoraproject.org//packages/python-distro/1.0.1/2.el7/noarch/python2-distro-1.0.1-2.el7.noarch.rpm
    - https://kojipkgs.fedoraproject.org/packages/bodhi/2.10.1/2.el7/noarch/python2-bodhi-2.10.1-2.el7.noarch.rpm
    - https://kojipkgs.fedoraproject.org/packages/bodhi/2.10.1/2.el7/noarch/bodhi-client-2.10.1-2.el7.noarch.rpm

- name: install tito and builddeps
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - tito
    - createrepo_c

- name: ensure builddeps are installed
  shell: yum-builddep origin.spec -y
  args:
    chdir: "{{ openshift_repo_path }}"

- name: build packages
  shell: tito build --test --rpm --rpmbuild-options="--define 'dist .el7'" --output={{ web_docroot }}/{{ project }}
  args:
    chdir: "{{ openshift_repo_path }}"
  register: pkgs_built

- name: generate repo
  shell: createrepo_c .
  args:
    chdir: "{{ web_docroot }}/{{ project }}/{{ arch }}"
  when: pkgs_built|success
