---
- name: Remove source for "{{ project }}"
  file:
    path: "{{ openshift_repo_path }}"
    state: absent

- name: Remove source for "{{ web_docroot }}/{{ project }}"
  file:
    path: "{{ web_docroot }}/{{ project }}"
    recurse: no
    state: absent

- name: Create {{ web_docroot }}/{{ project }}/{{ arch }}
  file:
    path: "{{ web_docroot }}/{{ project }}/{{ arch }}"
    state: directory
    owner: nginx
    group: nginx
    setype: httpd_sys_content_t