---

- name: "Create {{ openshift_repo_path }}"
  file:
    path: "{{ openshift_repo_path }}"
    state: directory

- name: "Check path exists"
  stat:
    path: "{{ openshift_repo_path }}.git/"
  register: dot_git_path

- name: "Setup default git configuration"
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "sig-paas" }
    - {name: "user.email", value: "sig-paas@centosproject.org" }

- name: "Git clone {{ project }}"
  git:
    repo: https://github.com/openshift/{{ project }}
    dest: "{{ openshift_repo_path }}"
    clone: yes
    update: yes
    accept_hostkey: yes
  when: (dot_git_path.stat.isdir is undefined) or
    (dot_git_path.stat.isdir == False)
