---
- include: cleanup_bfs.yml
  when: "cleanup|bool == true"
- include: clone_from_github.yml
- include: build_openshift_srpm_repo.yml
  when: "project == 'origin'"
- include: build_openshift-ansible_srpm.yml
  when: "project == 'openshift-ansible'"
## OLD WAY when we need to build full RPMs now just need source RPMS
#- include: cleanup_bfs.yml
#  when: "'repo_host' in group_names and cleanup"
#- include: clone_from_github.yml
#  when: "'repo_host' in group_names"
#- include: build_origin_repo.yml
#  when: "'repo_host' in group_names and project == 'origin'"
#- include: build_openshift-ansible_repo.yml
#  when: "'repo_host' in group_names and project == 'openshift-ansible'"
#- include: enable_openshift_repo.yml

