- name: install nginx
  yum: name=nginx state=present

- name: Configure nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}/nginx.conf"
    mode: 0644
  notify:
    - reload nginx

- name: Create {{ web_docroot }}/{{ project }}/{{ arch }}
  file:
    path: "{{ web_docroot }}/{{ project }}/{{ arch }}"
    state: directory
    owner: nginx
    group: nginx
    setype: httpd_sys_content_t

- name: Start the nginx service
  service: name=nginx state=started enabled=yes


