---

- name: "Get epel RPM signing key"
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: "Enable epel repo"
  template:
    src: roles/common/templates/epel-repo.j2
    dest: "/etc/yum.repos.d/epel.repo"
    mode: 0644
    owner: root
    group: root

