---
- stat: path="./{{ duffy_session_file }}"
  register: sf

- name: set duffy ssid
  shell: "cat ./{{ duffy_session_file }}"
  register: duffy_ssid
  when: sf.stat.exists

- name: teardown duffy instances
  duffy:
    state: "absent"
    ssid: "{{ duffy_ssid.stdout }}"
  register: teardown_result
  when: sf.stat.exists

#- debug:
#    var: teardown_result.status
#  when: sf.stat.exists

- name: remove inventory file
  file:
    path: "./{{ duffy_inventory_file }}"
    state: absent
  when: (sf.stat.exists and teardown_result.status == 'Done')

- name: remove session file
  file:
    path: "./{{ duffy_session_file }}"
    state: absent
  when: (sf.stat.exists and teardown_result.status == 'Done')

