- name: Install atomic-openshift-tests
  yum:
    name: origin-tests
    state: present
  when: not containerrun

- name: Install atomic-openshift-tests
  dnf:
    name: origin-tests
    state: present
  delegate_to: localhost
  when: containerrun
  ignore_errors: true
  register: dnf_out

- name: Set facts for rpm urls
  set_fact:
    origin_clients_rpm_url: "{{ origin_clients_rpm_url | default('https://cbs.centos.org/repos/paas7-openshift-origin36-testing/x86_64/os/Packages/origin-clients-3.6.1-1.0.008f2d5.x86_64.rpm') }}"
    origin_rpm_url: "{{ origin_rpm_url | default('https://cbs.centos.org/repos/paas7-openshift-origin36-testing/x86_64/os/Packages/origin-3.6.1-1.0.008f2d5.x86_64.rpm') }}"
    origin_tests_rpm_url: "{{ origin_tests_rpm_url | default('https://cbs.centos.org/repos/paas7-openshift-origin36-testing/x86_64/os/Packages/origin-tests-3.6.1-1.0.008f2d5.x86_64.rpm') }}"
    dnf_failed: "{{ dnf_out['failed'] | default(false)  }}"

- name: "Download rpms to /tmp/"
  get_url:
    url: "{{ item }}"
    dest: /tmp/
  with_items:
    - "{{ origin_clients_rpm_url }}"
    - "{{ origin_rpm_url }}"
    - "{{ origin_tests_rpm_url }}"
  delegate_to: localhost
  when: containerrun and dnf_failed

- name: "Install rpms"
  shell: "rpm -ivh /tmp/{{ item | basename }} --force"
  with_items:
    - "{{ origin_clients_rpm_url }}"
    - "{{ origin_rpm_url }}"
    - "{{ origin_tests_rpm_url }}"
  delegate_to: localhost
  when: containerrun and dnf_failed
