---
- name: install firewalld
  yum: name=firewalld state=present

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- firewalld: service=http permanent=true state=enabled
  notify:
    - reload firewalld

- name: openshift yum repo on all nodes
  template:
    src: yumrepo.j2
    dest: "/etc/yum.repos.d/{{ project }}-{{ groups['repo_host'][0] }}.repo"
    mode: 0644
    owner: root
    group: root

- name: clean yum repos
  command: yum clean all

