---
- include: clone_from_github.yml
  when: "'repo_host' in group_names"
- include: enable_openshift-future_repo.yml
  when: "'repo_host' in group_names"
- include: ../../common/tasks/enable_epel.yml
- include: ../../nginx/tasks/simple_nginx_server.yml
  when: "'repo_host' in group_names"
- include: build_openshift_repo.yml
  when: "'repo_host' in group_names"
- include: enable_openshift_repo.yml

